### ISSUE TITLE
Not able to turn on maintenance mode

### ISSUE THREAD

**Issue by dushyantagarwal** [dokku/dokku-maintenance#4] opened 2016-10-09 09:05 UTC
I get following error when I run `dokku maintenance:on my_app_name` 

```
cp: cannot create regular file ‘/home/dokku/my_app_name/nginx.conf.d/maintenance.conf’: Permission denied
```

**Comment by josegonzalez** [comment] 2017-02-08 19:56
I'm closing this. If it can't create that file, its because the permissions on that dir are screwed up, and it's not owned by `dokku:dokku`. That would be caused by something like editing that directory as another user (root?), so you can fix it by updating the ownership.

**Closed as completed by josegonzalez** 2017-02-08 19:56 UTC
